# Generated by Django 2.2.4 on 2019-08-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publish Date'),
        ),
    ]
